export const ROLES = {
  CUSTOMER: "CUSTOMER",
  GYM_OWNER: "GYM_OWNER",
  TRAINER: "TRAINER",
  SUPPLEMENT_PROVIDER: "SUPPLEMENT_PROVIDER",
  ADMIN: "ADMIN",
};

export const USER_STATUS = {
  PENDING: "PENDING",
  ACTIVE: "ACTIVE",
  BLOCKED: "BLOCKED",
  REJECTED: "REJECTED",
};

export const GYM_STATUS = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  SUSPENDED: "SUSPENDED",
};

export const PAYMENT_STATUS = {
  PENDING: "PENDING",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
  REFUNDED: "REFUNDED",
};

export const ORDER_STATUS = {
  PENDING: "PENDING",
  PROCESSING: "PROCESSING",
  SHIPPED: "SHIPPED",
  DELIVERED: "DELIVERED",
  CANCELLED: "CANCELLED",
};

export const PAYMENT_TYPES = {
  MEMBERSHIP: "MEMBERSHIP",
  TRAINER_SESSION: "TRAINER_SESSION",
  SUPPLEMENT_ORDER: "SUPPLEMENT_ORDER",
};
